# Prod development configuration

# Spring configurations
spring:
  # JDBC configuration
  datasource:
    url: jdbc:h2:file:./data/demo-db # H2 database file will be saved in the 'data' folder (file-based)
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate # Validate schema, do not auto-update (safe for production)
  h2:
    console:
      enabled: false # Disable H2 database console

# AWS Specific Storage Configuration
aws:
  # S3 Configuration for AWS
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}

# Logging configuration
logging:
  level:
    root: INFO
    com.example.s3integration: INFO
