# Local development configuration

# Spring configurations
spring:
  # JDBC configuration
  datasource:
    url: jdbc:h2:file:./data/demo-db # H2 database file will be saved in the 'data' folder (file-based)
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Automatically updates the database schema (other options: create, create-drop)
  h2:
    console:
      enabled: true # Enable H2 database console
      path: /h2-console # URL path for H2 console access, visit 'http://localhost:6660/h2-console'

# AWS Specific Storage Configuration
aws:
  # S3 Configuration for AWS
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:your-aws-s3-access-key}
    secret-key: ${AWS_S3_SECRET_KEY:your-aws-s3-secret-key}
    region: ${AWS_S3_REGION:your-aws-s3-region}
    bucket-name: ${AWS_S3_BUCKET_NAME:your-aws-s3-bucket-name}

# Logging configuration
logging:
  level:
    root: INFO
    com.example.s3integration: DEBUG
